---
- name: Install Bacula
  hosts: bacula_server
  become: true
  vars:
    bacula_password: "mybaculapassword"
  tasks:
    - name: Install Bacula packages
      yum:
        name:
          - bacula-director
          - bacula-client
          - bacula-storage
        state: present
      register: result

    - name: Set Bacula password
      command: echo "{{ bacula_password }}" | bconsole
      when: result.changed

- name: Configure Bacula
  hosts: bacula_server
  become: true
  vars:
    bacula_server_name: "bacula_server"
    bacula_storage_name: "bacula_storage"
    bacula_client_name: "bacula_client"
    bacula_storage_device: "FileStorage"
    bacula_storage_path: "/mnt/bacula_storage"
    bacula_fileset_name: "postgres"
    bacula_backup_job_name: "PostgresBackup"
    bacula_backup_job_schedule: "Weekly"
    bacula_backup_job_start_time: "22:00"
  tasks:
    - name: Configure Bacula Director
      template:
        src: director.conf.j2
        dest: /etc/bacula/bacula-dir.conf
      notify: restart bacula-director

    - name: Configure Bacula Storage
      template:
        src: storage.conf.j2
        dest: /etc/bacula/bacula-sd.conf
      notify: restart bacula-storage

    - name: Configure Bacula Client
      template:
        src: client.conf.j2
        dest: /etc/bacula/bacula-fd.conf
      notify: restart bacula-fd

- name: Schedule Bacula Backup Job
  hosts: bacula_server
  become: true
  vars:
    postgres_backup_script_path: "/root/postgres_backup.sh"
    postgres_backup_script_user: "postgres"
    postgres_backup_cron_schedule: "0 0 * * 1"
  tasks:
    - name: Create Postgres backup script
      template:
        src: postgres_backup.sh.j2
        dest

