---
- name: Install Bacula packages
  yum:
    name:
      - bacula-director
      - bacula-storage
      - bacula-client
    state: present
  when: director

- name: Install Bacula packages
  yum:
    name:
      - bacula-client
    state: present
  when: client

- name: Install PostgreSQL packages
  yum:
    name:
      - postgresql-server
    state: present
  when: director

- name: Create Bacula user
  user:
    name: bacula
    comment: "Bacula backup user"
    shell: /bin/false
    system: true

- name: Allow TCP ports
  iptables:
    chain: IN_public_allow
    protocol: tcp
    destination_port: "{{ item }}"
    jump: ACCEPT
    state: present
  with_items:
    - 9101
    - 9102
    - 9103
  when: director

#На всех хостах нужно создать
- name: Create Bacula directories
  file:
    path: "{{ item }}"
    state: directory
    owner: bacula
    group: bacula
    mode: '0750'
  with_items:
    - /etc/bacula
    - /var/lib/bacula
    - /var/log/bacula
    - /var/run/bacula

#Только на хосте с диретором была проблема с этим файлом
- name: Create bacula-dir.conms file
  file:
    path: /var/spool/bacula/bacula-dir.conms
    state: touch
    mode: '0644'
    owner: bacula
  when: director

- name: Create PostgreSQL user
  postgresql_user:
    db: mydatabase
    name: bacula
    password: "{{ bacula_pg_password }}"
    priv: SUPERUSER,CREATEDB,CREATEROLE
  when: director

- name: Copy Bacula configuration files
  template:
    src: "{{ item.src }}"
    dest: "{{ item.dest }}"
    mode: "{{ item.mode }}"
  with_items: "{{ bacula_configs }}"
  when: director

- name: Configure Bacula Director
  template:
    src: bacula-fd-client.conf.j2
    dest: /etc/bacula/bacula-fd.conf
    mode: '0640'
  when: client

- name: Configure Bacula services
  systemd:
    name: "{{ item }}"
    enabled: true
    state: started
  with_items:
    - bacula-dir
    - bacula-sd
    - bacula-fd
  when: director